### ISSUE TITLE
Unreadable Documentation Sections

### ISSUE THREAD

**Issue by eFrane** [botman/botman.io#15]
There appears to be a CSS error on note blocks in the documentation. Here's an example:

![screen shot 2018-01-27 at 15 21 58](https://user-images.githubusercontent.com/237165/35472774-d997d86c-0375-11e8-85ee-68cd15126f36.png)

(Taken from: https://botman.io/2.0/driver-slack)

**Comment by sschlein** [comment]
Sorry for the late reply but can you fix it an provide a PR?

**Comment by eFrane** [comment]
~I can. Could you give me a hint as to which repository I should go to for that?~ Nevermind that. Fix PR will arrive soon.

**Comment by eFrane** [comment]
So, unintended follow-up: Had to open two PRs (#17 for the fix, #18 to make the fix work on my machine)

I think this issue is done as the discussion can be finished in the PRs.
