### ISSUE TITLE
Include media attachment feature in this demo instance

### ISSUE THREAD

**Issue by rhurtik** [botman/botman.io#9]
Would it be a big deal to include the media attachment feature for the Web driver on  this demo instance ? I am referring to Botmag Tinker issue =>  https://github.com/botman/botman/issues/587 .

**Comment by ceyquem** [comment]
that would be great indeed :)

**Comment by christophrumpel** [comment]
Yeah that would be nice, but also a lot of other things right now to do. it is definitely going to happen but I can't tell you when. Maybe you can do a PR? Any help appreciated.
